avzone: melbourne-qh2-uom

volumes:
  - vol_name: v1
    vol_size: 125
  - vol_name: v2
    vol_size: 125
  - vol_name: v3
    vol_size: 125
  - vol_name: v4
    vol_size: 125

security_groups:
  - name: autossh
    description: "auto ssh"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autohttp
    description: "auto http"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autocdb
    description: "auto cdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoswarm
    description: "auto swarm"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autobk # backend debug
    description: "auto bk"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autocc # couchdb
    description: "auto cc"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoccc # couchdb
    description: "auto ccc"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoswarm2
    description: "auto swarm2"
    protocol: tcp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autotcc # automatically join CouchDB cluster
    description: "auto tcc"
    protocol: tcp
    port_range_min: 3001
    port_range_max: 3001
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoswarm2udp
    description: "auto swarmudp"
    protocol: udp
    port_range_min: 7946
    port_range_max: 7946
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoswarm2uudp
    description: "auto swarmuudp"
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoim
    description: "auto im"
    protocol: icmp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autopr # prometheus
    description: "auto pr"
    protocol: tcp
    port_range_min: 9090
    port_range_max: 9090
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
  - name: autoegress
    description: "auto egress"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
    direction: egress


instances:
  - name: n1
    volumes: [v1]
    flavor: uom.mse.2c9g
  - name: n2
    volumes: [v2]
    flavor: uom.mse.2c9g
  - name: n3
    volumes: [v3]
    flavor: uom.mse.2c9g
  - name: n4
    volumes: [v4]
    flavor: uom.mse.1c4g

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: zuomkey
# instance_flavor_2c8g: uom.mse.2c9g
