- name: copy scripts
  ansible.builtin.copy:
    src: "{{ local_script }}"
    dest: "{{ remote_script }}"
    mode: '0777'

- name: run scripts
  ansible.builtin.shell: "bash {{ remote_script }} > ~/sout.txt"