- name: joinswarm
  ansible.builtin.shell: "sudo docker swarm join --token {{ hostvars[groups[\"servers\"][0]][\"rawtoken2\"].stdout }} {{ groups[\"servers\"][0] }}:2377"
  # ansible.builtin.debug: var=servers[0]

- ansible.builtin.debug: var=hostvars[groups["servers"][0]]["rawtoken2"]